# Generated by Django 3.0.5 on 2020-05-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapperInstagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_ubicacion', models.CharField(max_length=100)),
                ('cantidad_publicaciones', models.CharField(max_length=100)),
            ],
        ),
    ]
