# Generated by Django 3.0.5 on 2020-05-18 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_scrapperinstagram'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapperComentarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_publicacion', models.CharField(max_length=100)),
                ('tipo_comentario', models.CharField(max_length=100)),
            ],
        ),
    ]
